<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_bringup</name>
  <version>2.0.0</version>
  <description>Paquete de despliegue y configuracion para manipulador de 3 GDL</description>
  <maintainer email="matiming123@gmail.com">Matías Molina</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencias de ejecución del launch -->
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>robot_control</exec_depend>
  <exec_depend>micro_ros_agent</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>