/**:
  ros__parameters:
    # -------------------------------------------------------------
    # 1. LÍMITES ARTICULARES (en radianes y grados para UI)
    # -------------------------------------------------------------
    joints:
      q1:
        min_deg: -90.0
        max_deg: 90.0
        min_rad: -1.5707963
        max_rad: 1.5707963
      q2:
        min_deg: 60.0
        max_deg: 157.0
        min_rad: 1.0471975
        max_rad: 2.7401669
      q3:
        min_deg: -25.0
        max_deg: 65.0
        min_rad: -0.4363323
        max_rad: 1.1344640

    # -------------------------------------------------------------
    # 2. PLANIFICACIÓN Y DINÁMICA (jtraj)
    # -------------------------------------------------------------
    planner:
      dt: 0.045                 # Paso de tiempo de discretización (45 ms)[cite: 1]
      max_joint_vel: 1.5        # Velocidad articular máxima (rad/s)[cite: 1]
      default_duration: 5.0     # Tiempo por defecto si no se especifica
      min_duration: 1.0         # Tiempo mínimo de seguridad

    # -------------------------------------------------------------
    # 3. PUNTOS CLAVE Y POSICIONES FIJAS (Espacio Cartesiano en m)
    # -------------------------------------------------------------
    kinematics:
      homing_position: [0.1723, 0.0, 0.17185][cite: 5]
      drop_off_point: [0.15275, -0.15275, 0.05][cite: 5]
      tool_z_offset: 0.04                      # Elevación de la base de piezas (40mm)[cite: 1]

    # -------------------------------------------------------------
    # 4. RED Y COMUNICACIONES DE VISIÓN
    # -------------------------------------------------------------
    vision_server:
      ip: "127.0.0.1"[cite: 5]
      port: 65432[cite: 5]
      timeout_sec: 5.0[cite: 5]
      max_retries: 3[cite: 5]